### ISSUE TITLE
Create repository

### ISSUE THREAD

**Issue by VladDaniliuk** [Shov-Studio/AllApis#1]
# Tasks
 - [x] Generate project. 
 - [x] Add detekt to project.
 - [x] Add buildSrc.
 - [x] Add keys for google and github releases.
 - [x] create github action for cheks:
 - - [x] check version up.
 - - [x] check new changelog.
 - - - [x] create CHANGELOG.md.
 - - [x] check detekt.
 - - - [x] create secrets.BOT_TOKEN for detekt action.
 - - [x] add check and coment the result.
 - [x] create github action for release.
 - - [x] get info from CHANGELOG.md for release. 
 - [x] create README.md.
 - - [x] add badges from [Shields IO](https://shields.io/)
 - - [x] add module scheme like in [old repo](https://github.com/VladDaniliuk/AllApis/blob/feature/ALLAPIS-1/README.md)
